// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/BANKA2017/mockbot/dao/model"
)

func newCheckin(db *gorm.DB, opts ...gen.DOOption) checkin {
	_checkin := checkin{}

	_checkin.checkinDo.UseDB(db, opts...)
	_checkin.checkinDo.UseModel(&model.Checkin{})

	tableName := _checkin.checkinDo.TableName()
	_checkin.ALL = field.NewAsterisk(tableName)
	_checkin.ID = field.NewInt32(tableName, "id")
	_checkin.UserID = field.NewString(tableName, "user_id")
	_checkin.Date = field.NewInt32(tableName, "date")

	_checkin.fillFieldMap()

	return _checkin
}

type checkin struct {
	checkinDo checkinDo

	ALL    field.Asterisk
	ID     field.Int32
	UserID field.String
	Date   field.Int32

	fieldMap map[string]field.Expr
}

func (c checkin) Table(newTableName string) *checkin {
	c.checkinDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c checkin) As(alias string) *checkin {
	c.checkinDo.DO = *(c.checkinDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *checkin) updateTableName(table string) *checkin {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.UserID = field.NewString(table, "user_id")
	c.Date = field.NewInt32(table, "date")

	c.fillFieldMap()

	return c
}

func (c *checkin) WithContext(ctx context.Context) *checkinDo { return c.checkinDo.WithContext(ctx) }

func (c checkin) TableName() string { return c.checkinDo.TableName() }

func (c checkin) Alias() string { return c.checkinDo.Alias() }

func (c checkin) Columns(cols ...field.Expr) gen.Columns { return c.checkinDo.Columns(cols...) }

func (c *checkin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *checkin) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["date"] = c.Date
}

func (c checkin) clone(db *gorm.DB) checkin {
	c.checkinDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c checkin) replaceDB(db *gorm.DB) checkin {
	c.checkinDo.ReplaceDB(db)
	return c
}

type checkinDo struct{ gen.DO }

func (c checkinDo) Debug() *checkinDo {
	return c.withDO(c.DO.Debug())
}

func (c checkinDo) WithContext(ctx context.Context) *checkinDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c checkinDo) ReadDB() *checkinDo {
	return c.Clauses(dbresolver.Read)
}

func (c checkinDo) WriteDB() *checkinDo {
	return c.Clauses(dbresolver.Write)
}

func (c checkinDo) Session(config *gorm.Session) *checkinDo {
	return c.withDO(c.DO.Session(config))
}

func (c checkinDo) Clauses(conds ...clause.Expression) *checkinDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c checkinDo) Returning(value interface{}, columns ...string) *checkinDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c checkinDo) Not(conds ...gen.Condition) *checkinDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c checkinDo) Or(conds ...gen.Condition) *checkinDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c checkinDo) Select(conds ...field.Expr) *checkinDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c checkinDo) Where(conds ...gen.Condition) *checkinDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c checkinDo) Order(conds ...field.Expr) *checkinDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c checkinDo) Distinct(cols ...field.Expr) *checkinDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c checkinDo) Omit(cols ...field.Expr) *checkinDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c checkinDo) Join(table schema.Tabler, on ...field.Expr) *checkinDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c checkinDo) LeftJoin(table schema.Tabler, on ...field.Expr) *checkinDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c checkinDo) RightJoin(table schema.Tabler, on ...field.Expr) *checkinDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c checkinDo) Group(cols ...field.Expr) *checkinDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c checkinDo) Having(conds ...gen.Condition) *checkinDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c checkinDo) Limit(limit int) *checkinDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c checkinDo) Offset(offset int) *checkinDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c checkinDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *checkinDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c checkinDo) Unscoped() *checkinDo {
	return c.withDO(c.DO.Unscoped())
}

func (c checkinDo) Create(values ...*model.Checkin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c checkinDo) CreateInBatches(values []*model.Checkin, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c checkinDo) Save(values ...*model.Checkin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c checkinDo) First() (*model.Checkin, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) Take() (*model.Checkin, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) Last() (*model.Checkin, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) Find() ([]*model.Checkin, error) {
	result, err := c.DO.Find()
	return result.([]*model.Checkin), err
}

func (c checkinDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Checkin, err error) {
	buf := make([]*model.Checkin, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c checkinDo) FindInBatches(result *[]*model.Checkin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c checkinDo) Attrs(attrs ...field.AssignExpr) *checkinDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c checkinDo) Assign(attrs ...field.AssignExpr) *checkinDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c checkinDo) Joins(fields ...field.RelationField) *checkinDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c checkinDo) Preload(fields ...field.RelationField) *checkinDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c checkinDo) FirstOrInit() (*model.Checkin, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) FirstOrCreate() (*model.Checkin, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) FindByPage(offset int, limit int) (result []*model.Checkin, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c checkinDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c checkinDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c checkinDo) Delete(models ...*model.Checkin) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *checkinDo) withDO(do gen.Dao) *checkinDo {
	c.DO = *do.(*gen.DO)
	return c
}
