// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCheckin = "checkin"

// Checkin mapped from table <checkin>
type Checkin struct {
	ID     int32  `gorm:"column:id;primaryKey" json:"id"`
	UserID string `gorm:"column:user_id" json:"user_id"`
	Date   int32  `gorm:"column:date" json:"date"`
}

// TableName Checkin's table name
func (*Checkin) TableName() string {
	return TableNameCheckin
}
