// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroupMessage = "group_message"

// GroupMessage mapped from table <group_message>
type GroupMessage struct {
	MessageID  string `gorm:"column:message_id;primaryKey" json:"message_id"`
	ChatID     string `gorm:"column:chat_id;primaryKey" json:"chat_id"`
	UserID     string `gorm:"column:user_id" json:"user_id"`
	FullName   string `gorm:"column:full_name" json:"full_name"`
	Date       int32  `gorm:"column:date" json:"date"`
	Text       string `gorm:"column:text" json:"text"`
	RawContent string `gorm:"column:raw_content" json:"raw_content"`
}

// TableName GroupMessage's table name
func (*GroupMessage) TableName() string {
	return TableNameGroupMessage
}
