// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	MessageID  string `gorm:"column:message_id;primaryKey" json:"message_id"`
	BotID      string `gorm:"column:bot_id" json:"bot_id"`
	ChatID     string `gorm:"column:chat_id;primaryKey" json:"chat_id"`
	Date       int32  `gorm:"column:date" json:"date"`
	Content    string `gorm:"column:content" json:"content"`
	RawContent string `gorm:"column:raw_content" json:"raw_content"`
	AutoDelete int32  `gorm:"column:auto_delete" json:"auto_delete"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
