// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStaff = "staff"

// Staff mapped from table <staff>
type Staff struct {
	UserID int32  `gorm:"column:user_id;primaryKey" json:"user_id"`
	Role   string `gorm:"column:role;not null" json:"role"`
	BotID  int32  `gorm:"column:bot_id;primaryKey" json:"bot_id"`
}

// TableName Staff's table name
func (*Staff) TableName() string {
	return TableNameStaff
}
